---
include:
  - board: xiao_ble
    shield: smatrix_left rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: xiao_ble
    shield: smatrix_right rgbled_adapter
  - board: xiao_ble

    shield: settings_reset
